### PR TITLE
interface: Add stake files from sdk with history

### PR DESCRIPTION
**Pull request by febo**
#### Problem

The initial PR #10 adds the Stake interface files from the SDK without their git history.

#### Summary of changes

Copy the files from the SDK together with their associated history using `git-filter-repo`:

```
# add the remote for the source repo
git remote add agave https://github.com/anza-xyz/agave.git
# fetch the master from agave under a different local branch
git fetch agave master:stake-from-agave
git switch stake-from-agave
# be safe, remove the remote
git remote rm agave
# filter the stake related files
python3 ../git-filter-repo \
--path sdk/program/src/stake/config.rs \
--path sdk/program/src/stake/instruction.rs  \
--path sdk/program/src/stake/mod.rs \
--path sdk/program/src/stake/stake_flags.rs \
--path sdk/program/src/stake/state.rs \
--path sdk/program/src/stake/tools.rs \
--path sdk/program/src/stake_history.rs \
--path-rename sdk/program/src/stake/config.rs:interface/src/config.rs \
--path-rename sdk/program/src/stake/instruction.rs:interface/src/instruction.rs \
--path-rename sdk/program/src/stake/mod.rs:interface/src/lib.rs \
--path-rename sdk/program/src/stake/stake_flags.rs:interface/src/stake_flags.rs \
--path-rename sdk/program/src/stake/state.rs:interface/src/state.rs \
--path-rename sdk/program/src/stake/tools.rs:interface/src/tools.rs \
--path-rename sdk/program/src/stake_history.rs:interface/src/stake_history.rs \
--force
# re-add this repo
git remote add origin https://github.com/febo/stake.git
git fetch origin master
git rebase master
```

### CODE REVIEW

**Comment by febo** [comment]
cc: @kevinheavey

**Comment by febo** [comment]
CI seems to be broken on `master`. I will fix it in a separate PR.

**Review by joncinque — APPROVED** [review]
Looks good to me! The one question is whether we want to include `sdk/program/src/sysvar/stake_history.rs`, but I think we can do that once the sysvar trait has been extracted

**Comment by joncinque** [comment]
It looks like this was squashed & merged instead of rebased & merged, so it doesn't put the whole history in the repo -- can you revert this and do it again with a rebase instead?

**Pull request merged**
